// <auto-generated />
namespace Endeavour.ObserverContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _17042014 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_17042014));
        
        string IMigrationMetadata.Id
        {
            get { return "201404170653558_17-04-2014"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
